//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.06 at 05:18:26 PM EEST 
//


package md.cnam.helpdesk.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Control complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Control">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AppRelativeTemplateSourceDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClientIDMode" type="{http://schemas.datacontract.org/2004/07/System.Web.UI}ClientIDMode" minOccurs="0"/>
 *         &lt;element name="EnableTheming" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="EnableViewState" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Page" type="{http://schemas.datacontract.org/2004/07/System.Web.UI}Page" minOccurs="0"/>
 *         &lt;element name="RenderingCompatibility" type="{http://schemas.datacontract.org/2004/07/System}Version" minOccurs="0"/>
 *         &lt;element name="Site" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="SkinID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TemplateControl" type="{http://schemas.datacontract.org/2004/07/System.Web.UI}TemplateControl" minOccurs="0"/>
 *         &lt;element name="ViewStateMode" type="{http://schemas.datacontract.org/2004/07/System.Web.UI}ViewStateMode" minOccurs="0"/>
 *         &lt;element name="Visible" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Control", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", propOrder = {
    "appRelativeTemplateSourceDirectory",
    "clientIDMode",
    "enableTheming",
    "enableViewState",
    "id",
    "page",
    "renderingCompatibility",
    "site",
    "skinID",
    "templateControl",
    "viewStateMode",
    "visible"
})
@XmlSeeAlso({
    PlaceHolder.class,
    TemplateControl.class
})
public class Control {

    @XmlElementRef(name = "AppRelativeTemplateSourceDirectory", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<String> appRelativeTemplateSourceDirectory;
    @XmlElement(name = "ClientIDMode")
    protected ClientIDMode clientIDMode;
    @XmlElement(name = "EnableTheming")
    protected Boolean enableTheming;
    @XmlElement(name = "EnableViewState")
    protected Boolean enableViewState;
    @XmlElementRef(name = "ID", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<String> id;
    @XmlElementRef(name = "Page", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<Page> page;
    @XmlElementRef(name = "RenderingCompatibility", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<Version> renderingCompatibility;
    @XmlElementRef(name = "Site", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<Object> site;
    @XmlElementRef(name = "SkinID", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<String> skinID;
    @XmlElementRef(name = "TemplateControl", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<TemplateControl> templateControl;
    @XmlElement(name = "ViewStateMode")
    protected ViewStateMode viewStateMode;
    @XmlElement(name = "Visible")
    protected Boolean visible;

    /**
     * Gets the value of the appRelativeTemplateSourceDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAppRelativeTemplateSourceDirectory() {
        return appRelativeTemplateSourceDirectory;
    }

    /**
     * Sets the value of the appRelativeTemplateSourceDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAppRelativeTemplateSourceDirectory(JAXBElement<String> value) {
        this.appRelativeTemplateSourceDirectory = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the clientIDMode property.
     * 
     * @return
     *     possible object is
     *     {@link ClientIDMode }
     *     
     */
    public ClientIDMode getClientIDMode() {
        return clientIDMode;
    }

    /**
     * Sets the value of the clientIDMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientIDMode }
     *     
     */
    public void setClientIDMode(ClientIDMode value) {
        this.clientIDMode = value;
    }

    /**
     * Gets the value of the enableTheming property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableTheming() {
        return enableTheming;
    }

    /**
     * Sets the value of the enableTheming property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableTheming(Boolean value) {
        this.enableTheming = value;
    }

    /**
     * Gets the value of the enableViewState property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableViewState() {
        return enableViewState;
    }

    /**
     * Sets the value of the enableViewState property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableViewState(Boolean value) {
        this.enableViewState = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setID(JAXBElement<String> value) {
        this.id = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the page property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Page }{@code >}
     *     
     */
    public JAXBElement<Page> getPage() {
        return page;
    }

    /**
     * Sets the value of the page property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Page }{@code >}
     *     
     */
    public void setPage(JAXBElement<Page> value) {
        this.page = ((JAXBElement<Page> ) value);
    }

    /**
     * Gets the value of the renderingCompatibility property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Version }{@code >}
     *     
     */
    public JAXBElement<Version> getRenderingCompatibility() {
        return renderingCompatibility;
    }

    /**
     * Sets the value of the renderingCompatibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Version }{@code >}
     *     
     */
    public void setRenderingCompatibility(JAXBElement<Version> value) {
        this.renderingCompatibility = ((JAXBElement<Version> ) value);
    }

    /**
     * Gets the value of the site property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     
     */
    public JAXBElement<Object> getSite() {
        return site;
    }

    /**
     * Sets the value of the site property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     
     */
    public void setSite(JAXBElement<Object> value) {
        this.site = ((JAXBElement<Object> ) value);
    }

    /**
     * Gets the value of the skinID property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSkinID() {
        return skinID;
    }

    /**
     * Sets the value of the skinID property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSkinID(JAXBElement<String> value) {
        this.skinID = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the templateControl property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TemplateControl }{@code >}
     *     
     */
    public JAXBElement<TemplateControl> getTemplateControl() {
        return templateControl;
    }

    /**
     * Sets the value of the templateControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TemplateControl }{@code >}
     *     
     */
    public void setTemplateControl(JAXBElement<TemplateControl> value) {
        this.templateControl = ((JAXBElement<TemplateControl> ) value);
    }

    /**
     * Gets the value of the viewStateMode property.
     * 
     * @return
     *     possible object is
     *     {@link ViewStateMode }
     *     
     */
    public ViewStateMode getViewStateMode() {
        return viewStateMode;
    }

    /**
     * Sets the value of the viewStateMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewStateMode }
     *     
     */
    public void setViewStateMode(ViewStateMode value) {
        this.viewStateMode = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVisible() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVisible(Boolean value) {
        this.visible = value;
    }

}
