//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.06 at 05:18:26 PM EEST 
//


package md.cnam.helpdesk.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HolderMenuClass complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HolderMenuClass">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IsValidRequest" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="myHolderMenu" type="{http://schemas.datacontract.org/2004/07/System.Web.UI.WebControls}PlaceHolder" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HolderMenuClass", namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", propOrder = {
    "isValidRequest",
    "message",
    "myHolderMenu"
})
public class HolderMenuClass {

    @XmlElement(name = "IsValidRequest")
    protected Boolean isValidRequest;
    @XmlElementRef(name = "Message", namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", type = JAXBElement.class)
    protected JAXBElement<String> message;
    @XmlElementRef(name = "myHolderMenu", namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", type = JAXBElement.class)
    protected JAXBElement<PlaceHolder> myHolderMenu;

    /**
     * Gets the value of the isValidRequest property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsValidRequest() {
        return isValidRequest;
    }

    /**
     * Sets the value of the isValidRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsValidRequest(Boolean value) {
        this.isValidRequest = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMessage(JAXBElement<String> value) {
        this.message = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the myHolderMenu property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PlaceHolder }{@code >}
     *     
     */
    public JAXBElement<PlaceHolder> getMyHolderMenu() {
        return myHolderMenu;
    }

    /**
     * Sets the value of the myHolderMenu property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PlaceHolder }{@code >}
     *     
     */
    public void setMyHolderMenu(JAXBElement<PlaceHolder> value) {
        this.myHolderMenu = ((JAXBElement<PlaceHolder> ) value);
    }

}
