//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.06 at 05:18:26 PM EEST 
//


package md.cnam.helpdesk.wsdl;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the md.cnam.helpdesk.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WebAuthorizationAttached_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "Attached");
    private final static QName _WebAuthorizationFullName_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "FullName");
    private final static QName _AnyURI_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyURI");
    private final static QName _WcfLoginData_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "WcfLoginData");
    private final static QName _Char_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "char");
    private final static QName _DateTime_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "dateTime");
    private final static QName _Control_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "Control");
    private final static QName _QName_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "QName");
    private final static QName _UnsignedShort_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedShort");
    private final static QName _ArrayOfKeyValueOfanyTypeanyType_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/Arrays", "ArrayOfKeyValueOfanyTypeanyType");
    private final static QName _Float_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "float");
    private final static QName _Long_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "long");
    private final static QName _Short_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "short");
    private final static QName _WebAuthorization_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "WebAuthorization");
    private final static QName _Base64Binary_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "base64Binary");
    private final static QName _Byte_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "byte");
    private final static QName _ViewStateEncryptionMode_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "ViewStateEncryptionMode");
    private final static QName _HolderMenuClass_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "HolderMenuClass");
    private final static QName _Boolean_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "boolean");
    private final static QName _TraceMode_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web", "TraceMode");
    private final static QName _ArrayOfUserList_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "ArrayOfUserList");
    private final static QName _Page_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "Page");
    private final static QName _TemplateControl_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "TemplateControl");
    private final static QName _MenuList_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "MenuList");
    private final static QName _UnsignedByte_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedByte");
    private final static QName _AnyType_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyType");
    private final static QName _UnsignedInt_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedInt");
    private final static QName _Int_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "int");
    private final static QName _Version_QNAME = new QName("http://schemas.datacontract.org/2004/07/System", "Version");
    private final static QName _ClientIDMode_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "ClientIDMode");
    private final static QName _Decimal_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "decimal");
    private final static QName _Double_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "double");
    private final static QName _Guid_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "guid");
    private final static QName _Duration_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "duration");
    private final static QName _ViewStateMode_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "ViewStateMode");
    private final static QName _String_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "string");
    private final static QName _UnsignedLong_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedLong");
    private final static QName _ParentMenuList_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "ParentMenuList");
    private final static QName _ArrayOfParentMenuList_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "ArrayOfParentMenuList");
    private final static QName _ArrayOfMenuList_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "ArrayOfMenuList");
    private final static QName _PlaceHolder_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI.WebControls", "PlaceHolder");
    private final static QName _UserList_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "UserList");
    private final static QName _GetParentMenuWcfTicket_QNAME = new QName("http://tempuri.org/", "wcfTicket");
    private final static QName _PageClientTarget_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "ClientTarget");
    private final static QName _PageMetaDescription_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "MetaDescription");
    private final static QName _PageTitle_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "Title");
    private final static QName _PageMetaKeywords_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "MetaKeywords");
    private final static QName _PageItems_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "Items");
    private final static QName _PageUICulture_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "UICulture");
    private final static QName _PageCulture_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "Culture");
    private final static QName _PageErrorPage_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "ErrorPage");
    private final static QName _PageStyleSheetTheme_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "StyleSheetTheme");
    private final static QName _PageResponseEncoding_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "ResponseEncoding");
    private final static QName _PageMasterPageFile_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "MasterPageFile");
    private final static QName _PageViewStateUserKey_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "ViewStateUserKey");
    private final static QName _PageContentType_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "ContentType");
    private final static QName _PageTheme_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "Theme");
    private final static QName _PageAutoPostBackControl_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "AutoPostBackControl");
    private final static QName _ExcahgePasswordResponseExcahgePasswordResult_QNAME = new QName("http://tempuri.org/", "ExcahgePasswordResult");
    private final static QName _HolderMenuClassMyHolderMenu_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "myHolderMenu");
    private final static QName _HolderMenuClassMessage_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "Message");
    private final static QName _TemplateControlAppRelativeVirtualPath_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "AppRelativeVirtualPath");
    private final static QName _WcfLoginDataTicket_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "Ticket");
    private final static QName _ControlID_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "ID");
    private final static QName _ControlSkinID_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "SkinID");
    private final static QName _ControlRenderingCompatibility_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "RenderingCompatibility");
    private final static QName _ControlSite_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "Site");
    private final static QName _ControlAppRelativeTemplateSourceDirectory_QNAME = new QName("http://schemas.datacontract.org/2004/07/System.Web.UI", "AppRelativeTemplateSourceDirectory");
    private final static QName _GetAutentificationInfoResponseGetAutentificationInfoResult_QNAME = new QName("http://tempuri.org/", "GetAutentificationInfoResult");
    private final static QName _MenuListUserFullName_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "UserFullName");
    private final static QName _MenuListRoute_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "Route");
    private final static QName _MenuListMenu_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "Menu");
    private final static QName _MenuListLink_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "Link");
    private final static QName _MenuListController_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "Controller");
    private final static QName _MenuListAction_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "Action");
    private final static QName _ParentMenuListParentName_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "ParentName");
    private final static QName _GetMenuResponseGetMenuResult_QNAME = new QName("http://tempuri.org/", "GetMenuResult");
    private final static QName _GetPlaceHolderMenuPageName_QNAME = new QName("http://tempuri.org/", "_pageName");
    private final static QName _GetPlaceHolderMenuCurentUsername_QNAME = new QName("http://tempuri.org/", "_curentUsername");
    private final static QName _GetPlaceHolderMenuResponseGetPlaceHolderMenuResult_QNAME = new QName("http://tempuri.org/", "GetPlaceHolderMenuResult");
    private final static QName _WcfLoginResponseWcfLoginResult_QNAME = new QName("http://tempuri.org/", "wcfLoginResult");
    private final static QName _GetUserListBySIResponseGetUserListBySIResult_QNAME = new QName("http://tempuri.org/", "GetUserListBySIResult");
    private final static QName _ExcahgePasswordNewPassword_QNAME = new QName("http://tempuri.org/", "NewPassword");
    private final static QName _ExcahgePasswordIsAuthorizated_QNAME = new QName("http://tempuri.org/", "IsAuthorizated");
    private final static QName _GetParentMenuResponseGetParentMenuResult_QNAME = new QName("http://tempuri.org/", "GetParentMenuResult");
    private final static QName _UserListUserMail_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "UserMail");
    private final static QName _UserListUserName_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "UserName");
    private final static QName _UserListUserIdnp_QNAME = new QName("http://schemas.datacontract.org/2004/07/WcfAutentificationService", "UserIdnp");
    private final static QName _WcfLoginWcfUser_QNAME = new QName("http://tempuri.org/", "wcfUser");
    private final static QName _WcfLoginWcfPassword_QNAME = new QName("http://tempuri.org/", "wcfPassword");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: md.cnam.helpdesk.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WebAuthorization }
     * 
     */
    public WebAuthorization createWebAuthorization() {
        return new WebAuthorization();
    }

    /**
     * Create an instance of {@link GetParentMenu }
     * 
     */
    public GetParentMenu createGetParentMenu() {
        return new GetParentMenu();
    }

    /**
     * Create an instance of {@link ExcahgePasswordResponse }
     * 
     */
    public ExcahgePasswordResponse createExcahgePasswordResponse() {
        return new ExcahgePasswordResponse();
    }

    /**
     * Create an instance of {@link TemplateControl }
     * 
     */
    public TemplateControl createTemplateControl() {
        return new TemplateControl();
    }

    /**
     * Create an instance of {@link Control }
     * 
     */
    public Control createControl() {
        return new Control();
    }

    /**
     * Create an instance of {@link GetMenu }
     * 
     */
    public GetMenu createGetMenu() {
        return new GetMenu();
    }

    /**
     * Create an instance of {@link ArrayOfParentMenuList }
     * 
     */
    public ArrayOfParentMenuList createArrayOfParentMenuList() {
        return new ArrayOfParentMenuList();
    }

    /**
     * Create an instance of {@link ArrayOfKeyValueOfanyTypeanyType.KeyValueOfanyTypeanyType }
     * 
     */
    public ArrayOfKeyValueOfanyTypeanyType.KeyValueOfanyTypeanyType createArrayOfKeyValueOfanyTypeanyTypeKeyValueOfanyTypeanyType() {
        return new ArrayOfKeyValueOfanyTypeanyType.KeyValueOfanyTypeanyType();
    }

    /**
     * Create an instance of {@link ParentMenuList }
     * 
     */
    public ParentMenuList createParentMenuList() {
        return new ParentMenuList();
    }

    /**
     * Create an instance of {@link GetPlaceHolderMenu }
     * 
     */
    public GetPlaceHolderMenu createGetPlaceHolderMenu() {
        return new GetPlaceHolderMenu();
    }

    /**
     * Create an instance of {@link PlaceHolder }
     * 
     */
    public PlaceHolder createPlaceHolder() {
        return new PlaceHolder();
    }

    /**
     * Create an instance of {@link GetPlaceHolderMenuResponse }
     * 
     */
    public GetPlaceHolderMenuResponse createGetPlaceHolderMenuResponse() {
        return new GetPlaceHolderMenuResponse();
    }

    /**
     * Create an instance of {@link ExcahgePassword }
     * 
     */
    public ExcahgePassword createExcahgePassword() {
        return new ExcahgePassword();
    }

    /**
     * Create an instance of {@link GetUserListBySIResponse }
     * 
     */
    public GetUserListBySIResponse createGetUserListBySIResponse() {
        return new GetUserListBySIResponse();
    }

    /**
     * Create an instance of {@link GetAutentificationInfo }
     * 
     */
    public GetAutentificationInfo createGetAutentificationInfo() {
        return new GetAutentificationInfo();
    }

    /**
     * Create an instance of {@link UserList }
     * 
     */
    public UserList createUserList() {
        return new UserList();
    }

    /**
     * Create an instance of {@link GetUserListBySI }
     * 
     */
    public GetUserListBySI createGetUserListBySI() {
        return new GetUserListBySI();
    }

    /**
     * Create an instance of {@link Page }
     * 
     */
    public Page createPage() {
        return new Page();
    }

    /**
     * Create an instance of {@link ArrayOfMenuList }
     * 
     */
    public ArrayOfMenuList createArrayOfMenuList() {
        return new ArrayOfMenuList();
    }

    /**
     * Create an instance of {@link HolderMenuClass }
     * 
     */
    public HolderMenuClass createHolderMenuClass() {
        return new HolderMenuClass();
    }

    /**
     * Create an instance of {@link WcfLoginData }
     * 
     */
    public WcfLoginData createWcfLoginData() {
        return new WcfLoginData();
    }

    /**
     * Create an instance of {@link ArrayOfKeyValueOfanyTypeanyType }
     * 
     */
    public ArrayOfKeyValueOfanyTypeanyType createArrayOfKeyValueOfanyTypeanyType() {
        return new ArrayOfKeyValueOfanyTypeanyType();
    }

    /**
     * Create an instance of {@link GetAutentificationInfoResponse }
     * 
     */
    public GetAutentificationInfoResponse createGetAutentificationInfoResponse() {
        return new GetAutentificationInfoResponse();
    }

    /**
     * Create an instance of {@link MenuList }
     * 
     */
    public MenuList createMenuList() {
        return new MenuList();
    }

    /**
     * Create an instance of {@link Version }
     * 
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link GetMenuResponse }
     * 
     */
    public GetMenuResponse createGetMenuResponse() {
        return new GetMenuResponse();
    }

    /**
     * Create an instance of {@link ArrayOfUserList }
     * 
     */
    public ArrayOfUserList createArrayOfUserList() {
        return new ArrayOfUserList();
    }

    /**
     * Create an instance of {@link WcfLoginResponse }
     * 
     */
    public WcfLoginResponse createWcfLoginResponse() {
        return new WcfLoginResponse();
    }

    /**
     * Create an instance of {@link GetParentMenuResponse }
     * 
     */
    public GetParentMenuResponse createGetParentMenuResponse() {
        return new GetParentMenuResponse();
    }

    /**
     * Create an instance of {@link WcfLogin }
     * 
     */
    public WcfLogin createWcfLogin() {
        return new WcfLogin();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "Attached", scope = WebAuthorization.class)
    public JAXBElement<String> createWebAuthorizationAttached(String value) {
        return new JAXBElement<String>(_WebAuthorizationAttached_QNAME, String.class, WebAuthorization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "FullName", scope = WebAuthorization.class)
    public JAXBElement<String> createWebAuthorizationFullName(String value) {
        return new JAXBElement<String>(_WebAuthorizationFullName_QNAME, String.class, WebAuthorization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "anyURI")
    public JAXBElement<String> createAnyURI(String value) {
        return new JAXBElement<String>(_AnyURI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WcfLoginData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "WcfLoginData")
    public JAXBElement<WcfLoginData> createWcfLoginData(WcfLoginData value) {
        return new JAXBElement<WcfLoginData>(_WcfLoginData_QNAME, WcfLoginData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "char")
    public JAXBElement<Integer> createChar(Integer value) {
        return new JAXBElement<Integer>(_Char_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "dateTime")
    public JAXBElement<XMLGregorianCalendar> createDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Control }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "Control")
    public JAXBElement<Control> createControl(Control value) {
        return new JAXBElement<Control>(_Control_QNAME, Control.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "QName")
    public JAXBElement<QName> createQName(QName value) {
        return new JAXBElement<QName>(_QName_QNAME, QName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedShort")
    public JAXBElement<Integer> createUnsignedShort(Integer value) {
        return new JAXBElement<Integer>(_UnsignedShort_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfKeyValueOfanyTypeanyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays", name = "ArrayOfKeyValueOfanyTypeanyType")
    public JAXBElement<ArrayOfKeyValueOfanyTypeanyType> createArrayOfKeyValueOfanyTypeanyType(ArrayOfKeyValueOfanyTypeanyType value) {
        return new JAXBElement<ArrayOfKeyValueOfanyTypeanyType>(_ArrayOfKeyValueOfanyTypeanyType_QNAME, ArrayOfKeyValueOfanyTypeanyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "float")
    public JAXBElement<Float> createFloat(Float value) {
        return new JAXBElement<Float>(_Float_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "long")
    public JAXBElement<Long> createLong(Long value) {
        return new JAXBElement<Long>(_Long_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "short")
    public JAXBElement<Short> createShort(Short value) {
        return new JAXBElement<Short>(_Short_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WebAuthorization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "WebAuthorization")
    public JAXBElement<WebAuthorization> createWebAuthorization(WebAuthorization value) {
        return new JAXBElement<WebAuthorization>(_WebAuthorization_QNAME, WebAuthorization.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "base64Binary")
    public JAXBElement<byte[]> createBase64Binary(byte[] value) {
        return new JAXBElement<byte[]>(_Base64Binary_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "byte")
    public JAXBElement<Byte> createByte(Byte value) {
        return new JAXBElement<Byte>(_Byte_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ViewStateEncryptionMode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "ViewStateEncryptionMode")
    public JAXBElement<ViewStateEncryptionMode> createViewStateEncryptionMode(ViewStateEncryptionMode value) {
        return new JAXBElement<ViewStateEncryptionMode>(_ViewStateEncryptionMode_QNAME, ViewStateEncryptionMode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HolderMenuClass }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "HolderMenuClass")
    public JAXBElement<HolderMenuClass> createHolderMenuClass(HolderMenuClass value) {
        return new JAXBElement<HolderMenuClass>(_HolderMenuClass_QNAME, HolderMenuClass.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "boolean")
    public JAXBElement<Boolean> createBoolean(Boolean value) {
        return new JAXBElement<Boolean>(_Boolean_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TraceMode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web", name = "TraceMode")
    public JAXBElement<TraceMode> createTraceMode(TraceMode value) {
        return new JAXBElement<TraceMode>(_TraceMode_QNAME, TraceMode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfUserList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "ArrayOfUserList")
    public JAXBElement<ArrayOfUserList> createArrayOfUserList(ArrayOfUserList value) {
        return new JAXBElement<ArrayOfUserList>(_ArrayOfUserList_QNAME, ArrayOfUserList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Page }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "Page")
    public JAXBElement<Page> createPage(Page value) {
        return new JAXBElement<Page>(_Page_QNAME, Page.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TemplateControl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "TemplateControl")
    public JAXBElement<TemplateControl> createTemplateControl(TemplateControl value) {
        return new JAXBElement<TemplateControl>(_TemplateControl_QNAME, TemplateControl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MenuList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "MenuList")
    public JAXBElement<MenuList> createMenuList(MenuList value) {
        return new JAXBElement<MenuList>(_MenuList_QNAME, MenuList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedByte")
    public JAXBElement<Short> createUnsignedByte(Short value) {
        return new JAXBElement<Short>(_UnsignedByte_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "anyType")
    public JAXBElement<Object> createAnyType(Object value) {
        return new JAXBElement<Object>(_AnyType_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedInt")
    public JAXBElement<Long> createUnsignedInt(Long value) {
        return new JAXBElement<Long>(_UnsignedInt_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "int")
    public JAXBElement<Integer> createInt(Integer value) {
        return new JAXBElement<Integer>(_Int_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Version }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System", name = "Version")
    public JAXBElement<Version> createVersion(Version value) {
        return new JAXBElement<Version>(_Version_QNAME, Version.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClientIDMode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "ClientIDMode")
    public JAXBElement<ClientIDMode> createClientIDMode(ClientIDMode value) {
        return new JAXBElement<ClientIDMode>(_ClientIDMode_QNAME, ClientIDMode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "decimal")
    public JAXBElement<BigDecimal> createDecimal(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Decimal_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "double")
    public JAXBElement<Double> createDouble(Double value) {
        return new JAXBElement<Double>(_Double_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "guid")
    public JAXBElement<String> createGuid(String value) {
        return new JAXBElement<String>(_Guid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "duration")
    public JAXBElement<Duration> createDuration(Duration value) {
        return new JAXBElement<Duration>(_Duration_QNAME, Duration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ViewStateMode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "ViewStateMode")
    public JAXBElement<ViewStateMode> createViewStateMode(ViewStateMode value) {
        return new JAXBElement<ViewStateMode>(_ViewStateMode_QNAME, ViewStateMode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "string")
    public JAXBElement<String> createString(String value) {
        return new JAXBElement<String>(_String_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedLong")
    public JAXBElement<BigInteger> createUnsignedLong(BigInteger value) {
        return new JAXBElement<BigInteger>(_UnsignedLong_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParentMenuList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "ParentMenuList")
    public JAXBElement<ParentMenuList> createParentMenuList(ParentMenuList value) {
        return new JAXBElement<ParentMenuList>(_ParentMenuList_QNAME, ParentMenuList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfParentMenuList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "ArrayOfParentMenuList")
    public JAXBElement<ArrayOfParentMenuList> createArrayOfParentMenuList(ArrayOfParentMenuList value) {
        return new JAXBElement<ArrayOfParentMenuList>(_ArrayOfParentMenuList_QNAME, ArrayOfParentMenuList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfMenuList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "ArrayOfMenuList")
    public JAXBElement<ArrayOfMenuList> createArrayOfMenuList(ArrayOfMenuList value) {
        return new JAXBElement<ArrayOfMenuList>(_ArrayOfMenuList_QNAME, ArrayOfMenuList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlaceHolder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI.WebControls", name = "PlaceHolder")
    public JAXBElement<PlaceHolder> createPlaceHolder(PlaceHolder value) {
        return new JAXBElement<PlaceHolder>(_PlaceHolder_QNAME, PlaceHolder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "UserList")
    public JAXBElement<UserList> createUserList(UserList value) {
        return new JAXBElement<UserList>(_UserList_QNAME, UserList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "wcfTicket", scope = GetParentMenu.class)
    public JAXBElement<String> createGetParentMenuWcfTicket(String value) {
        return new JAXBElement<String>(_GetParentMenuWcfTicket_QNAME, String.class, GetParentMenu.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "ClientTarget", scope = Page.class)
    public JAXBElement<String> createPageClientTarget(String value) {
        return new JAXBElement<String>(_PageClientTarget_QNAME, String.class, Page.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "MetaDescription", scope = Page.class)
    public JAXBElement<String> createPageMetaDescription(String value) {
        return new JAXBElement<String>(_PageMetaDescription_QNAME, String.class, Page.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "Title", scope = Page.class)
    public JAXBElement<String> createPageTitle(String value) {
        return new JAXBElement<String>(_PageTitle_QNAME, String.class, Page.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "MetaKeywords", scope = Page.class)
    public JAXBElement<String> createPageMetaKeywords(String value) {
        return new JAXBElement<String>(_PageMetaKeywords_QNAME, String.class, Page.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfKeyValueOfanyTypeanyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "Items", scope = Page.class)
    public JAXBElement<ArrayOfKeyValueOfanyTypeanyType> createPageItems(ArrayOfKeyValueOfanyTypeanyType value) {
        return new JAXBElement<ArrayOfKeyValueOfanyTypeanyType>(_PageItems_QNAME, ArrayOfKeyValueOfanyTypeanyType.class, Page.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "UICulture", scope = Page.class)
    public JAXBElement<String> createPageUICulture(String value) {
        return new JAXBElement<String>(_PageUICulture_QNAME, String.class, Page.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "Culture", scope = Page.class)
    public JAXBElement<String> createPageCulture(String value) {
        return new JAXBElement<String>(_PageCulture_QNAME, String.class, Page.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "ErrorPage", scope = Page.class)
    public JAXBElement<String> createPageErrorPage(String value) {
        return new JAXBElement<String>(_PageErrorPage_QNAME, String.class, Page.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "StyleSheetTheme", scope = Page.class)
    public JAXBElement<String> createPageStyleSheetTheme(String value) {
        return new JAXBElement<String>(_PageStyleSheetTheme_QNAME, String.class, Page.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "ResponseEncoding", scope = Page.class)
    public JAXBElement<String> createPageResponseEncoding(String value) {
        return new JAXBElement<String>(_PageResponseEncoding_QNAME, String.class, Page.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "MasterPageFile", scope = Page.class)
    public JAXBElement<String> createPageMasterPageFile(String value) {
        return new JAXBElement<String>(_PageMasterPageFile_QNAME, String.class, Page.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "ViewStateUserKey", scope = Page.class)
    public JAXBElement<String> createPageViewStateUserKey(String value) {
        return new JAXBElement<String>(_PageViewStateUserKey_QNAME, String.class, Page.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "ContentType", scope = Page.class)
    public JAXBElement<String> createPageContentType(String value) {
        return new JAXBElement<String>(_PageContentType_QNAME, String.class, Page.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "Theme", scope = Page.class)
    public JAXBElement<String> createPageTheme(String value) {
        return new JAXBElement<String>(_PageTheme_QNAME, String.class, Page.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Control }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "AutoPostBackControl", scope = Page.class)
    public JAXBElement<Control> createPageAutoPostBackControl(Control value) {
        return new JAXBElement<Control>(_PageAutoPostBackControl_QNAME, Control.class, Page.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WebAuthorization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ExcahgePasswordResult", scope = ExcahgePasswordResponse.class)
    public JAXBElement<WebAuthorization> createExcahgePasswordResponseExcahgePasswordResult(WebAuthorization value) {
        return new JAXBElement<WebAuthorization>(_ExcahgePasswordResponseExcahgePasswordResult_QNAME, WebAuthorization.class, ExcahgePasswordResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlaceHolder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "myHolderMenu", scope = HolderMenuClass.class)
    public JAXBElement<PlaceHolder> createHolderMenuClassMyHolderMenu(PlaceHolder value) {
        return new JAXBElement<PlaceHolder>(_HolderMenuClassMyHolderMenu_QNAME, PlaceHolder.class, HolderMenuClass.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "Message", scope = HolderMenuClass.class)
    public JAXBElement<String> createHolderMenuClassMessage(String value) {
        return new JAXBElement<String>(_HolderMenuClassMessage_QNAME, String.class, HolderMenuClass.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "AppRelativeVirtualPath", scope = TemplateControl.class)
    public JAXBElement<String> createTemplateControlAppRelativeVirtualPath(String value) {
        return new JAXBElement<String>(_TemplateControlAppRelativeVirtualPath_QNAME, String.class, TemplateControl.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "Ticket", scope = WcfLoginData.class)
    public JAXBElement<String> createWcfLoginDataTicket(String value) {
        return new JAXBElement<String>(_WcfLoginDataTicket_QNAME, String.class, WcfLoginData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "Message", scope = WcfLoginData.class)
    public JAXBElement<String> createWcfLoginDataMessage(String value) {
        return new JAXBElement<String>(_HolderMenuClassMessage_QNAME, String.class, WcfLoginData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "ID", scope = Control.class)
    public JAXBElement<String> createControlID(String value) {
        return new JAXBElement<String>(_ControlID_QNAME, String.class, Control.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TemplateControl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "TemplateControl", scope = Control.class)
    public JAXBElement<TemplateControl> createControlTemplateControl(TemplateControl value) {
        return new JAXBElement<TemplateControl>(_TemplateControl_QNAME, TemplateControl.class, Control.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "SkinID", scope = Control.class)
    public JAXBElement<String> createControlSkinID(String value) {
        return new JAXBElement<String>(_ControlSkinID_QNAME, String.class, Control.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Version }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "RenderingCompatibility", scope = Control.class)
    public JAXBElement<Version> createControlRenderingCompatibility(Version value) {
        return new JAXBElement<Version>(_ControlRenderingCompatibility_QNAME, Version.class, Control.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "Site", scope = Control.class)
    public JAXBElement<Object> createControlSite(Object value) {
        return new JAXBElement<Object>(_ControlSite_QNAME, Object.class, Control.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Page }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "Page", scope = Control.class)
    public JAXBElement<Page> createControlPage(Page value) {
        return new JAXBElement<Page>(_Page_QNAME, Page.class, Control.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", name = "AppRelativeTemplateSourceDirectory", scope = Control.class)
    public JAXBElement<String> createControlAppRelativeTemplateSourceDirectory(String value) {
        return new JAXBElement<String>(_ControlAppRelativeTemplateSourceDirectory_QNAME, String.class, Control.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "wcfTicket", scope = GetMenu.class)
    public JAXBElement<String> createGetMenuWcfTicket(String value) {
        return new JAXBElement<String>(_GetParentMenuWcfTicket_QNAME, String.class, GetMenu.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WebAuthorization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "GetAutentificationInfoResult", scope = GetAutentificationInfoResponse.class)
    public JAXBElement<WebAuthorization> createGetAutentificationInfoResponseGetAutentificationInfoResult(WebAuthorization value) {
        return new JAXBElement<WebAuthorization>(_GetAutentificationInfoResponseGetAutentificationInfoResult_QNAME, WebAuthorization.class, GetAutentificationInfoResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "UserFullName", scope = MenuList.class)
    public JAXBElement<String> createMenuListUserFullName(String value) {
        return new JAXBElement<String>(_MenuListUserFullName_QNAME, String.class, MenuList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "Route", scope = MenuList.class)
    public JAXBElement<String> createMenuListRoute(String value) {
        return new JAXBElement<String>(_MenuListRoute_QNAME, String.class, MenuList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "Menu", scope = MenuList.class)
    public JAXBElement<String> createMenuListMenu(String value) {
        return new JAXBElement<String>(_MenuListMenu_QNAME, String.class, MenuList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "Link", scope = MenuList.class)
    public JAXBElement<String> createMenuListLink(String value) {
        return new JAXBElement<String>(_MenuListLink_QNAME, String.class, MenuList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "Controller", scope = MenuList.class)
    public JAXBElement<String> createMenuListController(String value) {
        return new JAXBElement<String>(_MenuListController_QNAME, String.class, MenuList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "Attached", scope = MenuList.class)
    public JAXBElement<String> createMenuListAttached(String value) {
        return new JAXBElement<String>(_WebAuthorizationAttached_QNAME, String.class, MenuList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "Action", scope = MenuList.class)
    public JAXBElement<String> createMenuListAction(String value) {
        return new JAXBElement<String>(_MenuListAction_QNAME, String.class, MenuList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "ParentName", scope = ParentMenuList.class)
    public JAXBElement<String> createParentMenuListParentName(String value) {
        return new JAXBElement<String>(_ParentMenuListParentName_QNAME, String.class, ParentMenuList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfMenuList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "GetMenuResult", scope = GetMenuResponse.class)
    public JAXBElement<ArrayOfMenuList> createGetMenuResponseGetMenuResult(ArrayOfMenuList value) {
        return new JAXBElement<ArrayOfMenuList>(_GetMenuResponseGetMenuResult_QNAME, ArrayOfMenuList.class, GetMenuResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "wcfTicket", scope = GetPlaceHolderMenu.class)
    public JAXBElement<String> createGetPlaceHolderMenuWcfTicket(String value) {
        return new JAXBElement<String>(_GetParentMenuWcfTicket_QNAME, String.class, GetPlaceHolderMenu.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "_pageName", scope = GetPlaceHolderMenu.class)
    public JAXBElement<String> createGetPlaceHolderMenuPageName(String value) {
        return new JAXBElement<String>(_GetPlaceHolderMenuPageName_QNAME, String.class, GetPlaceHolderMenu.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "_curentUsername", scope = GetPlaceHolderMenu.class)
    public JAXBElement<String> createGetPlaceHolderMenuCurentUsername(String value) {
        return new JAXBElement<String>(_GetPlaceHolderMenuCurentUsername_QNAME, String.class, GetPlaceHolderMenu.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HolderMenuClass }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "GetPlaceHolderMenuResult", scope = GetPlaceHolderMenuResponse.class)
    public JAXBElement<HolderMenuClass> createGetPlaceHolderMenuResponseGetPlaceHolderMenuResult(HolderMenuClass value) {
        return new JAXBElement<HolderMenuClass>(_GetPlaceHolderMenuResponseGetPlaceHolderMenuResult_QNAME, HolderMenuClass.class, GetPlaceHolderMenuResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WcfLoginData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "wcfLoginResult", scope = WcfLoginResponse.class)
    public JAXBElement<WcfLoginData> createWcfLoginResponseWcfLoginResult(WcfLoginData value) {
        return new JAXBElement<WcfLoginData>(_WcfLoginResponseWcfLoginResult_QNAME, WcfLoginData.class, WcfLoginResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfUserList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "GetUserListBySIResult", scope = GetUserListBySIResponse.class)
    public JAXBElement<ArrayOfUserList> createGetUserListBySIResponseGetUserListBySIResult(ArrayOfUserList value) {
        return new JAXBElement<ArrayOfUserList>(_GetUserListBySIResponseGetUserListBySIResult_QNAME, ArrayOfUserList.class, GetUserListBySIResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "NewPassword", scope = ExcahgePassword.class)
    public JAXBElement<String> createExcahgePasswordNewPassword(String value) {
        return new JAXBElement<String>(_ExcahgePasswordNewPassword_QNAME, String.class, ExcahgePassword.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "IsAuthorizated", scope = ExcahgePassword.class)
    public JAXBElement<String> createExcahgePasswordIsAuthorizated(String value) {
        return new JAXBElement<String>(_ExcahgePasswordIsAuthorizated_QNAME, String.class, ExcahgePassword.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "wcfTicket", scope = ExcahgePassword.class)
    public JAXBElement<String> createExcahgePasswordWcfTicket(String value) {
        return new JAXBElement<String>(_GetParentMenuWcfTicket_QNAME, String.class, ExcahgePassword.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfParentMenuList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "GetParentMenuResult", scope = GetParentMenuResponse.class)
    public JAXBElement<ArrayOfParentMenuList> createGetParentMenuResponseGetParentMenuResult(ArrayOfParentMenuList value) {
        return new JAXBElement<ArrayOfParentMenuList>(_GetParentMenuResponseGetParentMenuResult_QNAME, ArrayOfParentMenuList.class, GetParentMenuResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "IsAuthorizated", scope = GetAutentificationInfo.class)
    public JAXBElement<String> createGetAutentificationInfoIsAuthorizated(String value) {
        return new JAXBElement<String>(_ExcahgePasswordIsAuthorizated_QNAME, String.class, GetAutentificationInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "wcfTicket", scope = GetAutentificationInfo.class)
    public JAXBElement<String> createGetAutentificationInfoWcfTicket(String value) {
        return new JAXBElement<String>(_GetParentMenuWcfTicket_QNAME, String.class, GetAutentificationInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "UserFullName", scope = UserList.class)
    public JAXBElement<String> createUserListUserFullName(String value) {
        return new JAXBElement<String>(_MenuListUserFullName_QNAME, String.class, UserList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "UserMail", scope = UserList.class)
    public JAXBElement<String> createUserListUserMail(String value) {
        return new JAXBElement<String>(_UserListUserMail_QNAME, String.class, UserList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "UserName", scope = UserList.class)
    public JAXBElement<String> createUserListUserName(String value) {
        return new JAXBElement<String>(_UserListUserName_QNAME, String.class, UserList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "UserIdnp", scope = UserList.class)
    public JAXBElement<String> createUserListUserIdnp(String value) {
        return new JAXBElement<String>(_UserListUserIdnp_QNAME, String.class, UserList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/WcfAutentificationService", name = "Attached", scope = UserList.class)
    public JAXBElement<String> createUserListAttached(String value) {
        return new JAXBElement<String>(_WebAuthorizationAttached_QNAME, String.class, UserList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "wcfUser", scope = WcfLogin.class)
    public JAXBElement<String> createWcfLoginWcfUser(String value) {
        return new JAXBElement<String>(_WcfLoginWcfUser_QNAME, String.class, WcfLogin.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "wcfPassword", scope = WcfLogin.class)
    public JAXBElement<String> createWcfLoginWcfPassword(String value) {
        return new JAXBElement<String>(_WcfLoginWcfPassword_QNAME, String.class, WcfLogin.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "wcfTicket", scope = GetUserListBySI.class)
    public JAXBElement<String> createGetUserListBySIWcfTicket(String value) {
        return new JAXBElement<String>(_GetParentMenuWcfTicket_QNAME, String.class, GetUserListBySI.class, value);
    }

}
