//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.06 at 05:18:26 PM EEST 
//


package md.cnam.helpdesk.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for Page complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Page">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.datacontract.org/2004/07/System.Web.UI}TemplateControl">
 *       &lt;sequence>
 *         &lt;element name="AsyncTimeout" type="{http://schemas.microsoft.com/2003/10/Serialization/}duration" minOccurs="0"/>
 *         &lt;element name="AutoPostBackControl" type="{http://schemas.datacontract.org/2004/07/System.Web.UI}Control" minOccurs="0"/>
 *         &lt;element name="Buffer" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ClientTarget" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CodePage" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Culture" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EnableEventValidation" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="EnableViewStateMac" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ErrorPage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Items" type="{http://schemas.microsoft.com/2003/10/Serialization/Arrays}ArrayOfKeyValueOfanyTypeanyType" minOccurs="0"/>
 *         &lt;element name="LCID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="MaintainScrollPositionOnPostBack" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="MasterPageFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaxPageStateFieldLength" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="MetaDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MetaKeywords" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ResponseEncoding" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SmartNavigation" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="StyleSheetTheme" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Theme" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TraceEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="TraceModeValue" type="{http://schemas.datacontract.org/2004/07/System.Web}TraceMode" minOccurs="0"/>
 *         &lt;element name="UICulture" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ViewStateEncryptionMode" type="{http://schemas.datacontract.org/2004/07/System.Web.UI}ViewStateEncryptionMode" minOccurs="0"/>
 *         &lt;element name="ViewStateUserKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Page", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", propOrder = {
    "asyncTimeout",
    "autoPostBackControl",
    "buffer",
    "clientTarget",
    "codePage",
    "contentType",
    "culture",
    "enableEventValidation",
    "enableViewStateMac",
    "errorPage",
    "items",
    "lcid",
    "maintainScrollPositionOnPostBack",
    "masterPageFile",
    "maxPageStateFieldLength",
    "metaDescription",
    "metaKeywords",
    "responseEncoding",
    "smartNavigation",
    "styleSheetTheme",
    "theme",
    "title",
    "traceEnabled",
    "traceModeValue",
    "uiCulture",
    "viewStateEncryptionMode",
    "viewStateUserKey"
})
public class Page
    extends TemplateControl
{

    @XmlElement(name = "AsyncTimeout")
    protected Duration asyncTimeout;
    @XmlElementRef(name = "AutoPostBackControl", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<Control> autoPostBackControl;
    @XmlElement(name = "Buffer")
    protected Boolean buffer;
    @XmlElementRef(name = "ClientTarget", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<String> clientTarget;
    @XmlElement(name = "CodePage")
    protected Integer codePage;
    @XmlElementRef(name = "ContentType", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<String> contentType;
    @XmlElementRef(name = "Culture", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<String> culture;
    @XmlElement(name = "EnableEventValidation")
    protected Boolean enableEventValidation;
    @XmlElement(name = "EnableViewStateMac")
    protected Boolean enableViewStateMac;
    @XmlElementRef(name = "ErrorPage", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<String> errorPage;
    @XmlElementRef(name = "Items", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<ArrayOfKeyValueOfanyTypeanyType> items;
    @XmlElement(name = "LCID")
    protected Integer lcid;
    @XmlElement(name = "MaintainScrollPositionOnPostBack")
    protected Boolean maintainScrollPositionOnPostBack;
    @XmlElementRef(name = "MasterPageFile", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<String> masterPageFile;
    @XmlElement(name = "MaxPageStateFieldLength")
    protected Integer maxPageStateFieldLength;
    @XmlElementRef(name = "MetaDescription", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<String> metaDescription;
    @XmlElementRef(name = "MetaKeywords", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<String> metaKeywords;
    @XmlElementRef(name = "ResponseEncoding", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<String> responseEncoding;
    @XmlElement(name = "SmartNavigation")
    protected Boolean smartNavigation;
    @XmlElementRef(name = "StyleSheetTheme", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<String> styleSheetTheme;
    @XmlElementRef(name = "Theme", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<String> theme;
    @XmlElementRef(name = "Title", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<String> title;
    @XmlElement(name = "TraceEnabled")
    protected Boolean traceEnabled;
    @XmlElement(name = "TraceModeValue")
    protected TraceMode traceModeValue;
    @XmlElementRef(name = "UICulture", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<String> uiCulture;
    @XmlElement(name = "ViewStateEncryptionMode")
    protected ViewStateEncryptionMode viewStateEncryptionMode;
    @XmlElementRef(name = "ViewStateUserKey", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<String> viewStateUserKey;

    /**
     * Gets the value of the asyncTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getAsyncTimeout() {
        return asyncTimeout;
    }

    /**
     * Sets the value of the asyncTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setAsyncTimeout(Duration value) {
        this.asyncTimeout = value;
    }

    /**
     * Gets the value of the autoPostBackControl property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Control }{@code >}
     *     
     */
    public JAXBElement<Control> getAutoPostBackControl() {
        return autoPostBackControl;
    }

    /**
     * Sets the value of the autoPostBackControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Control }{@code >}
     *     
     */
    public void setAutoPostBackControl(JAXBElement<Control> value) {
        this.autoPostBackControl = ((JAXBElement<Control> ) value);
    }

    /**
     * Gets the value of the buffer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBuffer() {
        return buffer;
    }

    /**
     * Sets the value of the buffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBuffer(Boolean value) {
        this.buffer = value;
    }

    /**
     * Gets the value of the clientTarget property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getClientTarget() {
        return clientTarget;
    }

    /**
     * Sets the value of the clientTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setClientTarget(JAXBElement<String> value) {
        this.clientTarget = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the codePage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodePage() {
        return codePage;
    }

    /**
     * Sets the value of the codePage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodePage(Integer value) {
        this.codePage = value;
    }

    /**
     * Gets the value of the contentType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getContentType() {
        return contentType;
    }

    /**
     * Sets the value of the contentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setContentType(JAXBElement<String> value) {
        this.contentType = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the culture property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCulture() {
        return culture;
    }

    /**
     * Sets the value of the culture property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCulture(JAXBElement<String> value) {
        this.culture = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the enableEventValidation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableEventValidation() {
        return enableEventValidation;
    }

    /**
     * Sets the value of the enableEventValidation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableEventValidation(Boolean value) {
        this.enableEventValidation = value;
    }

    /**
     * Gets the value of the enableViewStateMac property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableViewStateMac() {
        return enableViewStateMac;
    }

    /**
     * Sets the value of the enableViewStateMac property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableViewStateMac(Boolean value) {
        this.enableViewStateMac = value;
    }

    /**
     * Gets the value of the errorPage property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getErrorPage() {
        return errorPage;
    }

    /**
     * Sets the value of the errorPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setErrorPage(JAXBElement<String> value) {
        this.errorPage = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfKeyValueOfanyTypeanyType }{@code >}
     *     
     */
    public JAXBElement<ArrayOfKeyValueOfanyTypeanyType> getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfKeyValueOfanyTypeanyType }{@code >}
     *     
     */
    public void setItems(JAXBElement<ArrayOfKeyValueOfanyTypeanyType> value) {
        this.items = ((JAXBElement<ArrayOfKeyValueOfanyTypeanyType> ) value);
    }

    /**
     * Gets the value of the lcid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLCID() {
        return lcid;
    }

    /**
     * Sets the value of the lcid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLCID(Integer value) {
        this.lcid = value;
    }

    /**
     * Gets the value of the maintainScrollPositionOnPostBack property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMaintainScrollPositionOnPostBack() {
        return maintainScrollPositionOnPostBack;
    }

    /**
     * Sets the value of the maintainScrollPositionOnPostBack property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMaintainScrollPositionOnPostBack(Boolean value) {
        this.maintainScrollPositionOnPostBack = value;
    }

    /**
     * Gets the value of the masterPageFile property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMasterPageFile() {
        return masterPageFile;
    }

    /**
     * Sets the value of the masterPageFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMasterPageFile(JAXBElement<String> value) {
        this.masterPageFile = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the maxPageStateFieldLength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxPageStateFieldLength() {
        return maxPageStateFieldLength;
    }

    /**
     * Sets the value of the maxPageStateFieldLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxPageStateFieldLength(Integer value) {
        this.maxPageStateFieldLength = value;
    }

    /**
     * Gets the value of the metaDescription property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMetaDescription() {
        return metaDescription;
    }

    /**
     * Sets the value of the metaDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMetaDescription(JAXBElement<String> value) {
        this.metaDescription = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the metaKeywords property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMetaKeywords() {
        return metaKeywords;
    }

    /**
     * Sets the value of the metaKeywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMetaKeywords(JAXBElement<String> value) {
        this.metaKeywords = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the responseEncoding property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getResponseEncoding() {
        return responseEncoding;
    }

    /**
     * Sets the value of the responseEncoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setResponseEncoding(JAXBElement<String> value) {
        this.responseEncoding = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the smartNavigation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSmartNavigation() {
        return smartNavigation;
    }

    /**
     * Sets the value of the smartNavigation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSmartNavigation(Boolean value) {
        this.smartNavigation = value;
    }

    /**
     * Gets the value of the styleSheetTheme property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getStyleSheetTheme() {
        return styleSheetTheme;
    }

    /**
     * Sets the value of the styleSheetTheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setStyleSheetTheme(JAXBElement<String> value) {
        this.styleSheetTheme = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the theme property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTheme() {
        return theme;
    }

    /**
     * Sets the value of the theme property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTheme(JAXBElement<String> value) {
        this.theme = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTitle(JAXBElement<String> value) {
        this.title = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the traceEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTraceEnabled() {
        return traceEnabled;
    }

    /**
     * Sets the value of the traceEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTraceEnabled(Boolean value) {
        this.traceEnabled = value;
    }

    /**
     * Gets the value of the traceModeValue property.
     * 
     * @return
     *     possible object is
     *     {@link TraceMode }
     *     
     */
    public TraceMode getTraceModeValue() {
        return traceModeValue;
    }

    /**
     * Sets the value of the traceModeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link TraceMode }
     *     
     */
    public void setTraceModeValue(TraceMode value) {
        this.traceModeValue = value;
    }

    /**
     * Gets the value of the uiCulture property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getUICulture() {
        return uiCulture;
    }

    /**
     * Sets the value of the uiCulture property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setUICulture(JAXBElement<String> value) {
        this.uiCulture = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the viewStateEncryptionMode property.
     * 
     * @return
     *     possible object is
     *     {@link ViewStateEncryptionMode }
     *     
     */
    public ViewStateEncryptionMode getViewStateEncryptionMode() {
        return viewStateEncryptionMode;
    }

    /**
     * Sets the value of the viewStateEncryptionMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewStateEncryptionMode }
     *     
     */
    public void setViewStateEncryptionMode(ViewStateEncryptionMode value) {
        this.viewStateEncryptionMode = value;
    }

    /**
     * Gets the value of the viewStateUserKey property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getViewStateUserKey() {
        return viewStateUserKey;
    }

    /**
     * Sets the value of the viewStateUserKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setViewStateUserKey(JAXBElement<String> value) {
        this.viewStateUserKey = ((JAXBElement<String> ) value);
    }

}
