//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.06 at 05:18:26 PM EEST 
//


package md.cnam.helpdesk.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TemplateControl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TemplateControl">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.datacontract.org/2004/07/System.Web.UI}Control">
 *       &lt;sequence>
 *         &lt;element name="AppRelativeVirtualPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TemplateControl", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", propOrder = {
    "appRelativeVirtualPath"
})
@XmlSeeAlso({
    Page.class
})
public class TemplateControl
    extends Control
{

    @XmlElementRef(name = "AppRelativeVirtualPath", namespace = "http://schemas.datacontract.org/2004/07/System.Web.UI", type = JAXBElement.class)
    protected JAXBElement<String> appRelativeVirtualPath;

    /**
     * Gets the value of the appRelativeVirtualPath property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAppRelativeVirtualPath() {
        return appRelativeVirtualPath;
    }

    /**
     * Sets the value of the appRelativeVirtualPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAppRelativeVirtualPath(JAXBElement<String> value) {
        this.appRelativeVirtualPath = ((JAXBElement<String> ) value);
    }

}
