//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.06 at 05:18:26 PM EEST 
//


package md.cnam.helpdesk.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="wcfLoginResult" type="{http://schemas.datacontract.org/2004/07/WcfAutentificationService}WcfLoginData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "wcfLoginResult"
})
@XmlRootElement(name = "wcfLoginResponse")
public class WcfLoginResponse {

    @XmlElementRef(name = "wcfLoginResult", namespace = "http://tempuri.org/", type = JAXBElement.class)
    protected JAXBElement<WcfLoginData> wcfLoginResult;

    /**
     * Gets the value of the wcfLoginResult property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link WcfLoginData }{@code >}
     *     
     */
    public JAXBElement<WcfLoginData> getWcfLoginResult() {
        return wcfLoginResult;
    }

    /**
     * Sets the value of the wcfLoginResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link WcfLoginData }{@code >}
     *     
     */
    public void setWcfLoginResult(JAXBElement<WcfLoginData> value) {
        this.wcfLoginResult = ((JAXBElement<WcfLoginData> ) value);
    }

}
